export const GET_INITIAL_GRID = "GET_INITIAL_GRID";
export const GET_NEW_GRID_WITH_WALL_TOGGLED = "GET_NEW_GRID_WITH_WALL_TOGGLED";
export const CLEAR_PATH = "CLEAR_PATH";
export const GET_START_NODE = "GET_START_NODE";
export const GET_FINISH_NODE = "GET_FINISH_NODE";
